version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    ports:
      - "5050:5050"
    links:
      - mongo